# Generated by Django 4.2 on 2023-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslist',
            name='match',
            field=models.ManyToManyField(related_name='player', to='sports.match'),
        ),
    ]
